[package]
name = "l3"
version.workspace = true
edition.workspace = true

[lints]
workspace = true

[dependencies]
clap.workspace = true
l3_parser = { path = "../l3_parser" }
l3_compiler = { path = "../l3_compiler" }
l3_vm = { path = "../l3_vm" }
l3_ast = { path = "../l3_ast" }
l3_bytecode = { path = "../l3_bytecode" }

[dev-dependencies]
paste = "1.0"
