[package]
name = "l3_vm"
version.workspace = true
edition.workspace = true

[lints]
workspace = true

[dependencies]
l3_bytecode = { path = "../l3_bytecode" }
l3_runtime = { path = "../l3_runtime" }
l3_ast = { path = "../l3_ast" }
l3_location = { path = "../l3_location" }
slotmap.workspace = true
foldhash = "0.1.5"
rand.workspace = true
